version: '3.8'

services:
  coderbot:
    build: .
    ports:
      - "5007:5000"
    environment:
      - AGENT_ID=coderbot
      - AGENT_NAME=Coder Bot
      - REDIS_URL=redis://redis:6379
      - DB_URL=postgresql://user:password@postgres:5432/coderbot_db
    depends_on:
      - redis
      - postgres
    volumes:
      - ./volumes/ollama_models:/app/models
      - ./volumes/blenderbot:/app/blenderbot
    networks:
      - agent_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agent_network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=coderbot_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - agent_network

volumes:
  redis_data:
  postgres_data:

networks:
  agent_network:
    driver: bridge
